spring.application.name=sistema
spring.datasource.url=jdbc:mysql://localhost:3306/carnes_ahumados?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# Pon aquí tu contraseña de phpMyAdmin (si usas XAMPP por defecto suele estar vacía)
spring.datasource.password=

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# 'none' significa que Spring NO borrará ni creará las tablas, usará las que ya hiciste en SQL.
spring.jpa.hibernate.ddl-auto=validate
# Muestra en la consola de Java las consultas SQL que se están ejecutando (muy útil para corregir errores)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

# Cloudinary Configuration
cloudinary.cloud_name=deilpve0y
cloudinary.api_key=446325932711418
cloudinary.api_secret=FVFHUaj-xVtgwYHhj7qWBYtSbfU